package GUIs;

import java.awt.Dimension;
import java.awt.Toolkit;

import CONSTANTs.ConfigConstant;
import CONTROLLERs.ListenerPackages;
import CONTROLLERs.PubSub;
import MODELs.PackageData;
import MODELs.User;
import UTILs.Utility;

/**
 *
 * @author HuynhSang
 */
@SuppressWarnings("serial")
public class ConfirmCallDialog extends javax.swing.JFrame {

	private int clientId;
	private User owner;
	private PubSub pubsub;
	private ListenerPackages listenerPackages;
	
    /**
     * Creates new form NoticeDialog
     */
    public ConfirmCallDialog() {
        initComponents();
    }
    
    public ConfirmCallDialog(PubSub pubsub, User owner, int clientId, ListenerPackages listenerPackages){
    	this.pubsub = pubsub;
    	this.owner = owner;
    	this.clientId = clientId;
    	this.listenerPackages = listenerPackages;
    	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
                             
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        lblQuestion = new javax.swing.JLabel();
        btnAccept = new javax.swing.JButton();
        btnDecline = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation((int) (dimension.getWidth()/2) - 150,(int) (dimension.getHeight()/2) - 50);
        setResizable(false);
        setAlwaysOnTop(true);
        
        lblQuestion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuestion.setText("You have a new call request!");

        btnAccept.setText("Accept");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });

        btnDecline.setText("Decline");
        btnDecline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeclineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(btnAccept)
                .addGap(18, 18, 18)
                .addComponent(btnDecline)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAccept)
                    .addComponent(btnDecline))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    	PackageData data = new PackageData("notice", "response: accept", " ", 0, owner.getId() + "");
   		Utility.sendMsg(pubsub, Utility.constructJSON(data).getBytes(), ConfigConstant.prefixNotice + clientId, 0);
   		LiveStream callStream = new LiveStream(pubsub, owner, clientId);
   		callStream.setVisible(true);
   		callStream.setType("call");
   		callStream.initLiveStreamDevice(ConfigConstant.prefixTopic +"call" + owner.getId(), "call");
   		pubsub.subscribe(ConfigConstant.prefixTopic +"call" + clientId, 0);
   		listenerPackages.setControlCallStream(callStream);
   		/*listenerPackages.getControlMainUI().getBtnLiveStream().setEnabled(false);
   		listenerPackages.getControlMainUI().getBtnCallClient().setEnabled(false);*/
   		this.dispose();
    }                                         

    private void btnDeclineActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    	PackageData data = new PackageData("notice", "response: decline", " ", 0, owner.getId() + "");
   		Utility.sendMsg(pubsub, Utility.constructJSON(data).getBytes(), ConfigConstant.prefixNotice + clientId, 0);
   		this.dispose();
    }
    

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnDecline;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblQuestion;
    // End of variables declaration                   
}