package GUIs;

import java.awt.Dimension;
import java.awt.Toolkit;

@SuppressWarnings("serial")
public class InputBroker extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public InputBroker() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
                            
    private void initComponents() {

        lblBroker = new javax.swing.JLabel();
        txtBrokerInput = new javax.swing.JTextField();
        btnGoApp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation((int) (dimension.getWidth()/2) - 150,(int) (dimension.getHeight()/2) - 50);

        lblBroker.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBroker.setText("Broker:");

        btnGoApp.setText("OK");
        btnGoApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoAppActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBroker)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBrokerInput, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGoApp)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBroker)
                    .addComponent(txtBrokerInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGoApp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void btnGoAppActionPerformed(java.awt.event.ActionEvent evt) {                                         
        String broker = "tcp://" +txtBrokerInput.getText();
        if(!txtBrokerInput.getText().equals("")){
        	new Login(broker).setVisible(true);
        	this.dispose();
        }
    }                                        

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnGoApp;
    private javax.swing.JLabel lblBroker;
    private javax.swing.JTextField txtBrokerInput;
    // End of variables declaration                   
}